### PR TITLE
Paste image feature, fix #298

### LINKED ISSUE #298: Paste images from clipboard
How do you (or can you?) paste an image into an .adoc file?  The ["Markdown Navigator"](https://vladsch.com/product/markdown-navigator) plugin allows this.

Do you support, or plan to support, something similar?

Thank you,
-T

### PR DESCRIPTION
**Pull request by bbrenne**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**
Add an action in the toolbar and context menu to paste image from clipboard. Image can be a file (copied from intelliJ or from file system) or from a browser (I didn't test from an image editor).

### CODE REVIEW

**Comment by ahus1** [comment]
Looking at the code you've handled quite some cases here including file list and image paste!

I'll look at it over the next days. I wanted to close the JavaFX-getting-stuck issue first; quite annoying issue, I hope it is now fixed and further IDE freezes are properly prevented...

**Comment by ahus1** [comment]
Hi Benjamin,

I've done a review, and handled some edge cases: 
* when there is no image content in the clipboard, the user gets a dialog explaining what to do
* when the user copies multiple files, multiple images will be inserted
* when there is a project-local file, creating just a reference is the default

I found that `VfsUtilCore.getRelativePath` will return null if the file is not within the current project. As a first workaround I used `imageFile.getCanonicalPath();` to set it to the full path. But AsciiDoc will never render it that way as it expects a relative file. 

I wonder if instead of asking the user the logic should be coded the following way: 
* if the file is local to the project, create only a reference
* if the file is not within the project, copy the file first, then create a reference

What do you think?

**Comment by ahus1** [comment]
Hi Benjamin, one more question: the image you used for the icon: did you use a template? Where did you take it from? I want to make sure that the source has the right license restrictions. Thanks!

**Comment by bbrenne** [comment]
> 
> 
> Hi Benjamin, one more question: the image you used for the icon: did you use a template? Where did you take it from? I want to make sure that the source has the right license restrictions. Thanks!

No issue on the license side, I made the icons myself.

**Comment by bbrenne** [comment]
> I found that `VfsUtilCore.getRelativePath` will return null if the file is not within the current project. As a first workaround I used `imageFile.getCanonicalPath();` to set it to the full path. But AsciiDoc will never render it that way as it expects a relative file.
> 
> I wonder if instead of asking the user the logic should be coded the following way:
> 
>     * if the file is local to the project, create only a reference
> 
>     * if the file is not within the project, copy the file first, then create a reference
> 
> 
> What do you think?

I'm wondering how it works when you have a hierarchy of projects with sub-projects. On my side It's not rare that I have a big project and several sub-projects including one that handle the documentation. So the file is not necessarily in the same direct project but with the same ancestor. I don't know if it's easy to go up in the hierarchy of projects.

**Comment by ahus1** [comment]
> On my side It's not rare that I have a big project and several sub-projects including one that handle the documentation.

Ok, I understand that the fixed will not work for you. Let's keep the dialog. 

What about situations where `VfsUtilCore.getRelativePath` returns null. Should we keep the workaround of an absolute file (that will never work with AsciiDoc as far as I know), or should it maybe disable the radio option, so the user must select copy file?

**Comment by bbrenne** [comment]
> What about situations where `VfsUtilCore.getRelativePath` returns null. Should we keep the workaround of an absolute file (that will never work with AsciiDoc as far as I know), or should it maybe disable the radio option, so the user must select copy file?

If it never works with asciidoc, lets forget about absolute URL. 

If there is only one option left in case of null I'd would simply not show the dialog and go for the remaining option directly (copy). If you agree  I'm ok to make the change.

**Comment by ahus1** [comment]
I've switched to a different API. This now calculates relative URLs when the file is outside of the current project. Reading the API docs `getRelativePath` worked only if the image was in the same or a subfolder of the asciidoc file.

The API is deprecated in 2018.1, but the only API we have in 2017.2, therefore I'd like to keep it as I don't want to bump up the requirements of the plugin for now. 

Users will need to adjust the URLs if they use `imagesdir`, but that would be hard to automate as this can be set in multiple locations. 

For now I would think it is ready-to-be-merged. What do you think?

**Comment by bbrenne** [comment]
I agree, tell me if you want me to realign first.

**Comment by ahus1** [comment]
Did you mean rebase? No need to rebase, I'll merge it as is.

**Pull request merged**
