### PR TITLE
Resolves #356: Add plugin logo

### LINKED ISSUE #356: Add plugin icon
It would be nice to add an icon to the plugin.

### PR DESCRIPTION
**Pull request by ardlank**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Adding logo for plugin, to be seen in market

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this PR.

Reading the guidelines in the SDK linked in the parent ticket it asks for a inner margin of the logo. Given a 40px raster, the logo should have at least 2px margin at each side. With a logo that is very "filled" it asks for visual weight adjustment, so for the given logo this would mean 4px margin resulting in a size of 32px.

Looking at the image on my phone it looks to me that it doesn't have a margin.
Let me know if you want to give it a try to adjust the margin. 

If you find it tricky to adjust the image I am happy to lend a hand.

**Comment by ardlank** [comment]
@ahus1 Cant seem to figure it out. Could use the help

**Comment by ahus1** [comment]
I've resized the logo so that is 32x32px with a 4px margin. See below a screenshot from [Inkscape](https://inkscape.org/), an SVG editor, of the result. I've actually used [Affinity Designer](https://affinity.serif.com/designer/) for this (a commercial, but affordable vector graphics editor), but technically Inkscape would have worked as well.

image

Thank you for the pull request. I'll now merge it.

**Comment by ardlank** [comment]
Thanks @ahus1. I tried editing the SVG's values inside an editor..

**Pull request merged**
