### PR TITLE
Enable JavaFX on M1/M2 Macs

### LINKED ISSUE #1544: Kroki rendering SVG instead of PNG on Mac
## Observed vs. expected behavior

When I do a `./gradlew test`, 3 tests are failing. One of the failing tests is `testShouldRenderVega`, where the expectation is: `https://kroki.io/vega/png/eNqVV...` , but the actual result is `https://kroki.io/vega/eNqVV...`. As you can see, the difference is the PNG part. I'm not familiar with how Kroki works, and how it's making the distinction between png and svg, but maybe the Mac needs some extra dependency? I couldn't find it in the developer guide.

## Steps to reproduce

1. Buy mac
2. Run Gradle test

Alternatively, using a build matrix perhaps? (if you want, I might be able to copy our config from Datafaker)

## Environment

Mac M2

### PR DESCRIPTION
**Pull request by ahus1**
Closes #1544

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

## Checklist:

- [ ] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.

Creating the pull request triggers some automated tests.
See the [chapter building in the contributor's guide](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) to find out how to run them on your local machine.

### CODE REVIEW

**Comment by ahus1** [comment]
@bodiam - I prepared this PR with an updated check for 64 bit JVMs. Please give it a try and run this on your M2. 

I'm curious: 
* When running the currently released plugin in your IDE, can you switch the preview in the plugin's settings to JavaFX after you've installed "JavaFX Runtime for Plugins"? I assume there is no entry in the dropdown box. See below for a screenshot where the entry is present.
* When running the IDE (possibly with `./gradlew runIde`), can you switch the preview in the plugin's settings now to JavaFX? The JavaFX plugin should already be pre-installed when starting it like this.
* How doe the preview look like with JavaFX?
* Do the unit tests on the CLI now work?

image

Some more background on JavaFX: 
* It is the deprecated preview, as the JCEF preview is much more advanced and has more features. The JCEF preview has a developer console to inspect the HTML, and it nicely renders SVGs
* Probably the only reason it is still around is that Android Studio doesn't bundle JCEF, and some people run IntelliJ with a non-JetBrains runtime, which also doesn't include JCEF (mostly re-bundled IDEs in package managers on Linux). 

As written above, please let me know how the test results are, and if this PR should then be merged.

**Comment by bodiam** [comment]
Hi @ahus1 ,

I installed the JavaFX plugins, but this is my screen of the most recent released version, so no JavaFX WebView view there:
image

When I run `./gradlew runIde`, the JavaFX WebView is visible:
image

when I select JavaFX (even with the JavaFX runtime for plugins installed), I'm getting an error:

```
Error initializing JavaFX: No toolkit found

java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:274)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:268)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:159)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel$1.run(JavaFxHtmlPanel.java:229)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.runFX(JavaFxHtmlPanel.java:422)
	at org.asciidoc.intellij.editor.javafx.JavaFxHtmlPanel.lambda$new$1(JavaFxHtmlPanel.java:219)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:823)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:420)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1145)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:703)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:596)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:596)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1026)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1026)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:823)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

After that, the JavaFX option is gone from the dropdown. Because of the stacktrace, I can't test how it looks.

When I run `./gradlew test`, the build is now successful:

image

**Comment by ahus1** [comment]
Thank you for the detailed description of the behavior your see. 

> I installed the JavaFX plugins, but this is my screen of the most recent released version, so no JavaFX WebView view there:

This is expected. This is due to the current logic bundled in the AsciiDoc plugin that it won't show this option on Mac on ARM.

> When I run ./gradlew runIde, the JavaFX WebView is visible:

This is expected. This is due to the check that I changed. 

> when I select JavaFX (even with the JavaFX runtime for plugins installed), I'm getting an error:

This is unfortunate... This means that JavaFX (at least as packaged by JetBrains) is broken on M2. I have hoped for a different result.

> After that, the JavaFX option is gone from the dropdown.

This is kind of expected. There is a very hacky code in `JavaFxHtmlPanelProvider#isJavaFxStuck` that checks if a first attempt to initialize JavaFX failed. 

One final thing to verify: I'd like to verify that when using `./gradlew runIde` the JetBrains IDE is used and not the JDK running Gradle. 
To do this, run the command again, and choose the menu "Help | About". On my machine it shows that it is using the JetBrains JDK:

```
IntelliJ IDEA 2024.1 EAP (Community Edition)
Runtime version: 17.0.10+8-b1171.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

If this final test confirms that the correct JDK is used, I'll revert this change so JavaFX is permanently disabled on MacOS ARM. I will then modify the tests to not trigger the Mac specific behavior and therefore fail on Mac.

**Comment by bodiam** [comment]
This is my JDK info after running `./gradlew runIde`:

```
IntelliJ IDEA 2024.1 EAP (Community Edition)
Build #IC-241.11761.10, built on February 7, 2024
Runtime version: 17.0.10+8-b1171.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
Kotlin analyzer version: 2.0.0-dev-14103
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 12
Metal Rendering is ON
Registry:
  ide.plugins.snapshot.on.unload.fail=true
Non-Bundled Plugins:
  PsiViewer (241-SNAPSHOT)
  com.intellij.javafx (1.0.4)
  com.intellij.grazie.pro (0.3.275)
  org.asciidoctor.intellij.asciidoc (0.0.1)
Kotlin: 241.11761.10-IJ
```

**Comment by ahus1** [comment]
Friendly reminder ... when you have the time, please review. I might otherwise just merge it and hope for the best.

**Comment by bodiam** [comment]
Hi @ahus1 , just tested with the latest:

```
> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

BUILD SUCCESSFUL in 1m 19s
18 actionable tasks: 13 executed, 5 up-to-date
```

LGTM.

**Comment by ahus1** [comment]
Thank you for verifying this!

**Pull request merged**
