### PR TITLE
Save pictures from preview, fix #245

### LINKED ISSUE #245: Add option to save generated images from preview in a custom path
We are using asciidoc diagrams for our designs and internal documentation, and from time to time we want to get the generated image to send to someone or include in another "more traditional" document format (*cough* microsoft word *cough*).

To do that, we generate the build of the docs and we search for the images we want in the generated path. This takes time and requires naming all images.

So, I'd be really nice if we could have a "Save image" option from the preview, that opens a file browser similar to how "save as..." works. If not from preview, maybe show a list of images in some menu or the top bar would help a lot also.

### PR DESCRIPTION
**Pull request by bbrenne**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

If adding a **new feature**:
- [x] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**

fixes #245

### CODE REVIEW

**Comment by ahus1** [comment]
@bbrenne - thank you for developing this nice feature!

This pull request contained changes from the attributes PR that is now merged. I've rebased the changes on the latest master and force-pushed the changes. You'll probably need to check out the branch on the remote repository to a new local branch to continue working on this.

I pushed one change as a suggestion: my diagrams usually have a diagram name and therefore a file name I want to re-use when saving the image. Only when no proper name is provided the suggested file name should be image.png. 

Please give it a try if this also works for you. Depending on the diagrams there might be other file name patterns that are generated.

The kind of diagrams I use (with the file name as a second argument): 

````
[plantuml,plantuml-class]
----
class Foo {
}
----
````

When I save the file I get a generic JFileChooser that looked different than the rest of the IntelliJ UI. 

Other plugins like plantuml4idea use a FileChooserFactory, see  https://github.com/esteinberg/plantuml4idea/blob/master/src/org/plantuml/idea/action/AbstractSaveDiagramAction.java

Could you please try to use the FileChooserFactory here so that it has the same look and feel? 

Thank you very much!

**Comment by bbrenne** [comment]
Thank you for completing this small feature. I'll try with the FileChooserFactory.

To call the function I used double click. I would have prefer right click but I was unable to make it work (through onclick or oncontextmenu).

**Comment by bbrenne** [comment]
Should be better now.

**Comment by ahus1** [comment]
I now try to set a reasonable default folder (parent folder of the file), and memorize the previously used folder. I also ensure that for plantuml and some other diagrams always SVG and PNG files are created, so the user can choose the file type to be exported. (This is actually due to the fact that previously the plugin always showed the PNG in the preview only, and SVG preview in JavaFX is broken).

Thanks for sharing your thoughts about right-click. 

I found the following snippet that I copied over from the Markdown plugin in 2016 (!)

    // JavaFxHtmlPanel.java
    myWebView.setContextMenuEnabled(false);

This actually disabled the standard context menu of the WebView. This contains "copy image to clipboard", but also other useless options in this context. That's probably the reason why it was disabled in the first place. I consider saving the file to the file system and choosing from SVG and PNG more helpful than copying an image to the clipboard.

I committed a change that enables the context menu in the Java code, and then disables the context menu document level by adding a dummy handler, and changes the event from double click to right click.

I think it is now ready to merge. What do you think?

**Comment by bbrenne** [comment]
Nice find with the right click! Good idea with the format.

I've just tried it, it runs smooth! (right click is probably more intuitive)

I also think it's ready to be merged.

**Comment by ahus1** [comment]
@bbrenne - thank you for taking on the issue and testing my change! I merged it, let's get some feedback from other users.

**Comment by abelsromero** [comment]
I tested the feature so far and is great. The only thing missing for me is some visual indication.
I am afraid not everyone will be aware of the feature unless they click accidentally on an image.

**Comment by ahus1** [comment]
@abelsromero - I've opened #282 to collect ideas for UX improvements.

**Pull request merged**
