### PR TITLE
Drive the right-click action from JavaFX. Fixes #283

### LINKED ISSUE #283: Save image context menu not showing up on macOS
Using macOS 10.14.5 with IntelliJ 2019.1.3 and IntelliJ Asciidoc plugin 0.28.5, the right-click option to save a (plantuml) diagram that is rendered by the plugin is not working.

### PR DESCRIPTION
**Pull request by wimdeblauwe**
…ript

as it does not seem to work on macOS

Fixes #283

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

### CODE REVIEW

**Comment by ahus1** [comment]
I confirm your code works on Windows as well! 

I've removed the JavaScript click handling code and refactored the code a bit.

@wimdeblauwe - Could you please give it a short test run on MacOS. Once it works for you, I'll merge it an create a fresh pre-release.

**Comment by wimdeblauwe** [comment]
I can confirm it works on macOS like this. However, 2 things I have noticed, but maybe we should tackle those separately:

1. If you do this:
```
[plantuml,svg]
```
Then the default name is `svg`.

If you do:
```
[plantuml]
```
Then the default name is `image`

If you do
```
[plantuml,my-diagram,svg]
```
Then the default filename is `my-diagram`

2. It is not possible to select `png` or `svg` output in the macOS save dialog:
image

3. The file is saved without extension (E.g. just `image`, not `image.png`)

**Comment by wimdeblauwe** [comment]
Did another test and if you manually type the extension, then it does get taken into account (E.g. if you type `my-image.png`, you get a PNG. If you type `my-image.svg`, you get an SVG.

**Comment by ahus1** [comment]
Thanks for testing it, i now merge it.

**Comment by ahus1** [comment]
The preview always contains a PNG image, as JavaFX can only show PNG properly. SVGs get often distorted. plantuml-png-patch.rb takes care to overwrite any user setting.

Therefore the right-click always finds a PNG first. Then the code tries to locate a SVG with the same name. On Windows the two extensions lead to a dropdown box. Unfortunately not on MacOS; there one probably needs to select the file type explicitly first.

When using the block attribute, the second attribute is always the name of the diagram file to be created. The third defines the file type. In order define a file type, you need to define a file name. You can leave out either the file type or the file type and the file name. 

The file name needs to be distinct for all diagrams you create, otherwise they will overwrite each other. You'll only see that in the output :-(

If you don't specify the file name, a random image name is created. 

The save dialog uses either the specified file name or maps a random image name to "image"

Again, this can be improved. Please open a new issue for this, or comment on the #282 issue if you think this fits best in there.

**Pull request merged**
