### PR TITLE
Add support for PacketDiag, RackDiag, Vega, Vega-Lite and WaveDrom

### PR DESCRIPTION
**Pull request by Mogztter**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Does this PR introduce a breaking change?** (check one)

- [X] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [x] New/updated tests are included

**Other information:**

Enable RackDiag, PacketDiag, Vega, Vega-Lite and WaveDrom support when using Kroki.

### CODE REVIEW

**Comment by Mogztter** [comment]
@ahus1 I'm fixing the error and I'm adding new tests. I've noticed that the error message if not explicit because we are using `Assert.assertTrue(html.contains("..."))`. Do you have an idea on how to improve things? Should I write a custom assertion/matcher ?

**Comment by ahus1** [comment]
There very minimal option would be to include the contents as part of the message as in `Assert.assertTrue(message, condition)`. 

I'm personally a fan of AssertJ, I wouldn't mind to add it as a dependency. This should contain a matcher that fits. Feel free to change only the tests you need/want to improve, and leave the rest for another PR.

As IntelliJ uses JUnit4 internally I wouldn't add JUnit5 for now as mixing both versions in the same project is possible, but cases confusion.

**Comment by Mogztter** [comment]
> I'm personally a fan of AssertJ,

Me too :blush: 

> There very minimal option would be to include the contents as part of the message as in Assert.assertTrue(message, condition).
> I wouldn't mind to add it as a dependency. This should contain a matcher that fits. Feel free to change only the tests you need/want to improve, and leave the rest for another PR.

Ok, I will prepare another PR to add AssertJ.

> As IntelliJ uses JUnit4 internally I wouldn't add JUnit5 for now as mixing both versions in the same project is possible, but cases confusion.

Fair enough :+1:

**Comment by ahus1** [comment]
@Mogztter - the latest version on master includes AssertJ, to use it in this PR please rebase the branch.

One of the tests in this branch fails. Do you have time to check the failing test, or should I have a look?

**Comment by Mogztter** [comment]
Sorry I lost track of this pull request, I will take care of it 😉

**Comment by Mogztter** [comment]
> the latest version on master includes AssertJ, to use it in this PR please rebase the branch.

Done.

> One of the tests in this branch fails. Do you have time to check the failing test, or should I have a look?

Rebased on master and now the test failure is gone :thinking:

**Comment by ahus1** [comment]
Thank you for your contribution! Will be part of the next pre-release.

**Comment by ahus1** [comment]
This is now available in release 0.30.69 that I've published today (yes, this is a regular release, not a pre-release) 🎉

**Comment by Mogztter** [comment]
Yay! thanks @ahus1

**Pull request merged**
