### PR TITLE
adding embedded split view and optional JavaFX WebView preview

### LINKED ISSUE #109: Feature: Add dual-panel support
Like jetbrains markdown plugin <https://plugins.jetbrains.com/plugin/7793>.

### PR DESCRIPTION
**Pull request by ahus1**
This PR uses an integrated preview plus adds optional JavaFX WebView rendering when available. 

It borrows *heavily* from JetBrains' open sourced [Markdown plugin]( https://github.com/JetBrains/intellij-plugins/tree/master/markdown) (including icons). 

This should fix #109, #101

### CODE REVIEW

**Comment by ahus1** [comment]
Here's a screenshot how the preview looks for example with tables when JavaFX preview is active. All the stands CSS styles for tables work nicely.

javafx-preview

**Comment by harrol** [comment]
Nice!

**Comment by mojavelinux** [comment]
Extremely, extremely nice. This is a game changer!

**Comment by bodiam** [comment]
@mojavelinux Dan, could you give Alexander push rights on the repo?

**Comment by mojavelinux** [comment]
I've sent Alexander an invitation.

For the future, my understanding is that you should be able to add members to the team. Let me know if my understanding is incorrect. https://github.com/orgs/asciidoctor/teams/intellij-plugin

**Comment by bodiam** [comment]
Yeah, that's what I tried, but either I missed the option, or it's not possible.

Doesn't matter, I'm not adding people that often anyway :)

**Comment by mojavelinux** [comment]
I just promoted you to team maintainer, so that might be what I needed to do. But I'm also happy to do it at your request.

**Comment by ahus1** [comment]
Thank you for all the encouraging comments. Expect a release of this feature in August. Until then I attach a preview release to this note that you can install manually via "Install plugin from disk...". Feedback is welcome.

Known issue: Darcula support for the preview in non-existent for JavaFX for now. 

[asciidoctor-intellij-PR118-v0_1.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/365340/asciidoctor-intellij-PR118-v0_1.zip)

**Comment by Mogztter** [comment]
Just updated this is awesome!
Thanks @ahus1 :+1:

**Pull request merged**
