### PR TITLE
Support for relative path links in preview html.

### PR DESCRIPTION
**Pull request by bbrenne**
This takes care of #204

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this pull request! I will have a look later today or tomorrow!

**Comment by bbrenne** [comment]
> 
> 
> This takes care of #204

Not sure about if it fix or not the #180.

**Comment by ahus1** [comment]
I've reviewed the code. It worked very well; I especially like the functionality to select a folder in the project view if it is a directory!

I pushed one commit to your branch that mostly handles some edge cases I saw. Please review my changes; if they work for you as well I'll merge the PR.

I've tested locally the following syntax for links:

```
<<reffile#id>>

link:reffile.adoc[]

link:reffile.html[]

link:reffile[]

link:reffile.adoc#id[]

link:reffile.html#id[]

link:reffile#id[]
```

The things I changed:

* call openInEditor() only in case of `"file".equalsIgnoreCase(scheme) || scheme == null` to avoid security issues, and log a warning in all other cases
* depending on whether `link:file[]` or <<ref#,file>> are used, the URL might contain no extension, .html or the real file name - I added two more tries that try to append .adoc and replace .html with .adoc to resolve the file
* I was unable to trigger LocalFileSystem.getInstance().findFileByPath(), therefore I removed the block. It seems strange to me that an absolute file name tries to look up something outside of the opened project. 
* For AsciiDocUtil.findId() I've added a variant with targetFile, as the anchor should be in that file, not in any other file
* reverting the re-formatted imports, adjusting some whitespace to align with project defaults

Again, please let me know if the changes work for you as well, then I'll merge the PR

**Comment by bbrenne** [comment]
Thanks for the corrections, I was thinking the scheme was the first part of the URL and that we would be forced to put file:// in front of all relative links but after testing it works great. Sorry about the formatting I'm using the one of the company which is quite different from the one this project.
The changes works for me as well you can merge :).

**Pull request merged**
