### PR TITLE
Implementing syntax highlighting for monospace with backticks (`)

### PR DESCRIPTION
**Pull request by romixch**
At Hackergarten Luzern (https://www.meetup.com/de-DE/Hackergarten-Luzern/events/235617923/) @ehmkah and I implemented Feature #161 .

We are not yet sure if the flex part is correctly and appropriately implemented. There is maybe a cleaner way. But we could not yet figure out which.

Also I ask myself how we could also implement features like bold and italic. Still this is a beginning.

### CODE REVIEW

**Comment by ehmkah** [comment]
Main question we did not understand how we can implement the parser in a way that that it does not make individual AsciidocTypes for each monospace character. See the https://github.com/romixch/asciidoctor-intellij-plugin/blob/ad1319b717f327c6b7008c7667f301896121b863/src/test/java/org/asciidoc/intellij/lexer/AsciiDocLexerTest.java testMonospace. 

But at least it is working.

**Comment by ahus1** [comment]
Thanks for contributing this (including the test case)! 

The option to collapse the monospace characters is hidden inside `AsciiDocTokenTypes`: add MONOSPACE to TOKENS_TO_MERGE and it should work as expected.

I wonder if you could also try to parse monospace text with a line break:

```
normal `green break
with` should work as well
```

If you run into problems please drop me a line.

Best regards,
Alexander

**Comment by romixch** [comment]
Thanks for your hint to TOKENS_TO_MERGE! I guess I managed it now to also support multilines. Although Asciidoctor itself seams not to support it. Or does it?

**Comment by mojavelinux** [comment]
> Although Asciidoctor itself seams not to support it. Or does it?

Yes, Asciidoctor supports formatted text that spans contiguous lines.

**Comment by ehmkah** [comment]
@mojavelinux - we cheked all cases which make the`on the next line or left it. But forget the obvious one - test whether line could be continued. Okay - am interested how my fix will look like ;-)

**Comment by ehmkah** [comment]
Normally a line command like e.g. ==, //, switches monospace of? My small test 
``monospace

== heading`

Does make a heading and leaves `monospace as it was written. (No monospace)

**Comment by ahus1** [comment]
@ehmkah, @romixch - I've done a test run and found the following: the syntax highlighting in the PR shows more green in the editor on the left than there is rendered monospace in the preview on the right. Asciidoc will recognize monospace only when the backticks are closed, while the parser will show the green already when there is a first backtick. 

Example: 

```
Or we leave the `open and then
// make a comment
```

I'm not sure if this is what people will expect.

I tried to do some look ahead rules, but I didn't really succeed. Especially multiline seems to be quite complex. 

The other thing I noticed: The constrained/unconstrained thing applies also to monospace, see http://asciidoctor.org/docs/user-manual/#constrained-quotes for more details. This boils down to blanks and non-word-characters next to the backticks should be considered. 

```
thisis`not`monospaceAsThereAreNoBlanks
this is `mono` space as there are blanks
```

I've added some logic to FormatAsciiDocAction#isWord some time ago that is used in editor actions triggered from the toolbar, but I don't know how to transfer this to a Flex grammar.

I'm not very familiar with parsers so I can't advise if it should be solved with more rules, more state variables in the lexer, additional post-processing or something else.

**Comment by mojavelinux** [comment]
> Normally a line command like e.g. ==, //, switches monospace of? My small test
> ``monospace
>
> == heading``

A blank line ends the paragraph and therefore ends the formatting.

Line comments, on the other hand, are dropped before parsing, so they just get cut away.

**Comment by ehmkah** [comment]
After an other hackergarden I have an idea how to solve it. The week beginnn 2016-12-21 I take the time to implement it. :-)

**Comment by ahus1** [comment]
@ehmkah - I've just accepted a PR that changed the build to Gradle. I hope that makes developing and contributing easier.

**Comment by romixch** [comment]
I think we have some trouble with the lexer here. When we want to highlight bold sequences or correctly highlight monospace inside titles it gets messy. We need some kind of a tree.

There are different solutions for that:

- Redesign the asciidoc.flex to have a real syntax tree.
- Use the real AsciiDoctor with JRuby with our own renderer which creates the original tree to use in the editor
- Don't implement this features
- Continue the work on https://github.com/asciidoctor/asciidoc-grammar-prototype

The last solution has some great advantages: One could use this not just for IntelliJ but also for Eclipse and other projects. Finally it could be the only source of truth for parsing AsciiDoc-Files?

**Comment by ahus1** [comment]
Regarding the options you describe: 

> Redesign the asciidoc.flex to have a real syntax tree.
> Continue the work on https://github.com/asciidoctor/asciidoc-grammar-prototype

I'm not very familiar with parsers - but I doubt the this kind or parser really fits the Asciidoc structure. But this stems only from my limited experience to add the header parsing to the existing grammar. I think this kind of parsers might not be the way to go for Asciidoc as it is quite different.

> Use the real AsciiDoctor with JRuby with our own renderer which creates the original tree to use in the editor

Sounds interesting, but I have no idea on how to do this. Can you point to an example?

Another idea: 

* there is AsciidocFX http://asciidocfx.com/ - it's also Java and open source. Maybe we could borrow concepts or codes from them as they are doing syntax highlighting already. I looked at their github repo, but didn't find the syntax highlighter straight away.

Do you want to explore the AsciidocFX path further?

**Comment by romixch** [comment]
Thnx for your reply. AsciidocFx sounds interesting. Going to have a look at their solution. Maybe not before the next hackergarden. But the next one is coming for sure!

**Comment by romixch** [comment]
Last Hackergarden @reinhapa and I tried to understand JFlex. We did some small examples outside of asciidoctor-intellij-plugin and had a look at other projects using JFlex. Now I think I understand how JFlex works an how we could implement the features in a clean way. Will take another approach at the next Hackergarden.

**Comment by mojavelinux** [comment]
> Use the real AsciiDoctor with JRuby with our own renderer which creates the original tree to use in the editor

Asciidoctor doesn't yet build a tree for inline nodes. You can find an early prototype here: https://github.com/Mogztter/asciidoctor-inline-parser

**Comment by ahus1** [comment]
I'm closing this PR in favor of the changes done in #244 - the next (pre)-release will support bold/mono/italic. Please follow #244 for the progress on this.

**Pull request closed without merging**
