### PR TITLE
Update AsciiDocDownloaderUtil.java to fix #1413

### LINKED ISSUE #1413: pandoc on apple silicon
## Observed vs. expected behavior

On my windows machine, "paste formatted" works perfect. On my M2pro Mac, it does nothing at all. When I take a look at the notifications window, I see

"AsciiDoc Download - Download PanDoc sucessful"

written in an endless loop

## Steps to reproduce

Copy an HTML table to the copy buffer and use the "paste formatted" button on a Mac with Apple Silicon

## Environment

Plugin Version: 0.38.20

IntelliJ Details: 

IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023

Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.2.4)
    com.intellij.plugin.adernov.powershell (2.0.10)
    PlantUML integration (6.3.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    Pythonid (231.9392.1)
    org.intellij.grails (231.8770.17)

Kotlin: 231-1.8.21-IJ9392.1

### PR DESCRIPTION
**Pull request by rdmueller**
This PR should fix https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1413

Not tested yet.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

## Checklist:

- [x] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.

Creating the pull request triggers some automated tests.
See the [chapter building in the contributor's guide](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) to find out how to run them on your local machine.

### CODE REVIEW

**Comment by ahus1** [comment]
Hi @rdmueller - thank you for the contribution. Unfortunately Checkstyle complains about the variable name. I've prepared this PR - please have a look and merge it. It should then be fine: https://github.com/docToolchain/asciidoctor-intellij-plugin/pull/1

**Comment by ahus1** [comment]
Thank you for your contribution. I will publish a prerelease soon.

**Comment by rdmueller** [comment]
that would make testing easier. thanx.

**Comment by ahus1** [comment]
Pre-release 0.39.2 is now available and ready for a test run. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Pull request merged**
