### PR TITLE
docs-565: add keymap for Windows/Linux users

### PR DESCRIPTION
**Pull request by EEM86**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
Added most important shortcuts for Windows/Linux users. If there are no changes needed, I'll update the file with shortcuts for Mac users.

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks, that looks really great. 

Looking though the codes, I haven't used "Generate code..." with AsciiDoc - can you describe how you use it? 

Please add backtick  `` ` ``  as a shortcut, it will monospace the selected text. 

Please go ahead an add Mac shortcuts. Do you plan a separate page, or will you put them on the same page?

**Comment by EEM86** [comment]
> 
> 
> Thanks, that looks really great.
> 
> Looking though the codes, I haven't used "Generate code..." with AsciiDoc - can you describe how you use it?
> 
> Please add backtick `` ` `` as a shortcut, it will monospace the selected text.
> 
> Please go ahead an add Mac shortcuts. Do you plan a separate page, or will you put them on the same page?

Yeah, there are few commands that seem are not be implemented for now. 
Alt+Insert for code generation (I'm not familiar with the plugin yet, so I thought it can generate default blocks or something else)
Also, Ctrl+Space and Ctrl+Shift+Space have no ideas for code completion.

Should I remove them until implementation for these keys will be released?
I'm going to add your addition and the version for Mac users in the same page. I think I'll update PR today.

**Comment by ahus1** [comment]
Then please remove Alt+Insert as the plugin doesn't implement code generation.

Ctrl+Space and Ctrl+Shift+Space work, for example when users reference files in includes they are auto-completed. Therefore keep them in the list.

Please go ahead and add the Mac information; looking forward to the PR.

**Comment by ahus1** [comment]
Thanks a lot for contributing this keymap! It will help writers that use the IDE to find their way around. 
I hope you enjoyed contributing!

**Pull request merged**
