### PR TITLE
Fix custom extensions loading when multimodule project

### PR DESCRIPTION
**Pull request by o-nix**
## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

This PR fixes custom plugins not being loaded from `.asciidoctor/lib` directory when the project consists of multiple submodules in different locations.

image

## Checklist:

- [ ] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.

Creating the pull request triggers some automated tests.
See the [chapter building in the contributor's guide](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) to find out how to run them on your local machine.

### CODE REVIEW

**Comment by o-nix** [comment]
@ahus1 👋

**Comment by ahus1** [comment]
Thank you for this PR. I had a look and found that to get the roots the `AsciiDocUtil.getRoots()` should be used as it handles also an additional case when here is a root folder which is not a module root. 

Unfortunately this method didn't return a `VirtualFile` which made it hard to test it, so this change had several knock-on effects.

I also found that `AsciiDocApplicationSettings` should now handle roots, and and not project base dirs. 

I set up a small test project and the changes I pushed just now worked for me locally. Could you please give them a try as well?

**Comment by o-nix** [comment]
Thanks!
I think it started collecting even from not "actively visible/opened" roots. My root project is tied to an empty folder so it is not visible. Only submodules in other folders are visible, after they are imported via `New -> Module from existing sources...`. This gives the full focus on submodules inside one opened project.
The newer version automatically picked up the `.asciidoctor/lib` folder from that "not visible root" directory. I had to delete the extra plugin.
On the one hand, it is perfectly fine, but on the other, it could be solved further by not collecting **all** JARs per the whole project, but only looking at the direct parent folder of the currently rendered adoc. I do know that my simple patch also lacked this.

**Comment by verhas** [comment]
Could I politely ask you to explain to me what this bug is?

I maintain Jamal, which is integrated with Asciidoctor as a preprocessor, it has a lot of modules and extensions by itself, and I did not experience any problem in the past years. What do I miss?

**Comment by o-nix** [comment]
@verhas submodules must be imported into IDEA from completely different folders, not just a parent one.

**Comment by verhas** [comment]
1. Multi-module: Is the Asciidoctor extension or the project documented? I assume the second. Also, Jamal is documented using Jamal and asciidoctor, being both the extension and a documented multi-module project.

2. I will check in 24 hours, but as far as I remember, there is a JS submodule i. Jamal is implementing a JS-based debugger, which is not imported into IntelliJ, and it does have a README.adoc.jam, which I never experienced a problem with.

**Comment by o-nix** [comment]
> 1. Multi-module: Is the Asciidoctor extension or the project documented?

Both! 🙂
The magic folder is inside one of the modules, not in the root project's folder.

**Comment by o-nix** [comment]
@ahus1 since last week the updated PR's version has worked very well for me. Probably good to go and merge?

**Comment by ahus1** [comment]
Thank you for testing it in your environment. I'll merge it, still it will be some more days before I publish a new pre-release.

**Comment by ahus1** [comment]
There is now a new pre-release 0.42.0 that includes this change. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Pull request merged**
