### PR TITLE
Fix #583

### LINKED ISSUE #583: Ensure that test methods start with either "test" or "should"
The convention for unit test methods is to start with "test" or "should". 

A good way to ensure this would be an ArchUnit test. This framework is already in use within this project, see  ClassNameConventionsTest

See https://www.archunit.org/ for more information.

### PR DESCRIPTION
**Pull request by idosal**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [x] Other, please describe:

added enforcement to test method naming convention (#583)

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by idosal** [comment]
@ahus1 This is the test's output:
`Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsEmptyForNonPngJpegFiles()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsEmptyWhenFileIsNull()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsOptionWithActualFileWidth()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.psi.AsciiDocSectionTest.verifyIdContainsSeparators()> does not match '[should,test](.*?)' in (AsciiDocSectionTest.java:0)
Method <org.asciidoc.intellij.psi.AsciiDocSectionTest.verifyMatchingIdIgnoresSuffix()> does not match '[should,test](.*?)' in (AsciiDocSectionTest.java:0)
Method <org.asciidoc.intellij.ui.components.AttributeCheckBoxTest.invokesSelectedActionOnStateChange()> does not match '[should,test](.*?)' in (AttributeCheckBoxTest.java:0)
Method <org.asciidoc.intellij.ui.components.AttributeCheckBoxTest.isSetupCorrectly()> does not match '[should,test](.*?)' in (AttributeCheckBoxTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.ignoresFutureResultWhenCompletesWithAnEmptyOptionalButStillInvokesRunnable()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.isSetupCorrectly()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.returnsEmptyOptionWhenValueIsZero()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.returnsOptionWhenValueIsAPositiveInteger()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'Test method names should begin with 'test' or 'should'' was violated (11 times):
Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsEmptyForNonPngJpegFiles()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsEmptyWhenFileIsNull()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.actions.asciidoc.ImageServiceTest.returnsOptionWithActualFileWidth()> does not match '[should,test](.*?)' in (ImageServiceTest.java:0)
Method <org.asciidoc.intellij.psi.AsciiDocSectionTest.verifyIdContainsSeparators()> does not match '[should,test](.*?)' in (AsciiDocSectionTest.java:0)
Method <org.asciidoc.intellij.psi.AsciiDocSectionTest.verifyMatchingIdIgnoresSuffix()> does not match '[should,test](.*?)' in (AsciiDocSectionTest.java:0)
Method <org.asciidoc.intellij.ui.components.AttributeCheckBoxTest.invokesSelectedActionOnStateChange()> does not match '[should,test](.*?)' in (AttributeCheckBoxTest.java:0)
Method <org.asciidoc.intellij.ui.components.AttributeCheckBoxTest.isSetupCorrectly()> does not match '[should,test](.*?)' in (AttributeCheckBoxTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.ignoresFutureResultWhenCompletesWithAnEmptyOptionalButStillInvokesRunnable()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.isSetupCorrectly()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.returnsEmptyOptionWhenValueIsZero()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)
Method <org.asciidoc.intellij.ui.components.ImageWidthFieldTest.returnsOptionWhenValueIsAPositiveInteger()> does not match '[should,test](.*?)' in (ImageWidthFieldTest.java:0)`

**Comment by ahus1** [comment]
Well done!

Yes, renaming/prefixing should do the trick. If you think some test method should be re-worded to make clear behavior it verifies, please do.

Please rename the new class from "TestMethodNameConventionsTest" to "MethodNameConventionsTest", then it is in-line with "ClassNameConventionsTest".

Please push further changes to this PR. I can later squash the commits before I merge them.

**Comment by idosal** [comment]
Will do. Thanks.

**Comment by idosal** [comment]
@ahus1 should be fine now. :)

**Comment by ahus1** [comment]
Thanks for taking the time to refactor the code! I hope you found working with ArchUnit interesting.

**Pull request merged**
