### PR TITLE
Feature/java fx preview

### PR DESCRIPTION
**Pull request by bit-man**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [X] Other, please describe: Enahncement

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [X] New/updated tests are included

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

### CODE REVIEW

**Comment by ahus1** [comment]
@bit-man - I've cherry-picked the changes for #347, thank you for the additional labels. I did some additional changes to the properties (some unicode characters broke), so you need to rebase this PR.

For the changes regarding #331 I'm not sure why the property myShowJavaFxPreviewInstructions is placed in AsciiDocPreviewSettings as from my point of view AsciiDocPreviewSettings only holds settings provided by the user. At first glance myShowJavaFxPreviewInstructions is something that is evaluated at runtime, and not saved in the settings.

Could this be changed so that it is evaluated at run time every time? Thanks!

**Comment by bit-man** [comment]
@ahus1 just rebased this PR

Regarding the `myShowJavaFxPreviewInstructions` makes sense to be available in user settings then the user can revert it. Otherwise once instructed to not be show at editor panel the setting wouldn't be available anymore reverting the feature to the previous problem :(

Do you agree?

**Comment by ahus1** [comment]
@bit-man I tried you the PR locally and I'm afraid it doesn't match the situation I had im mind when writing #331.

The situation in #331 is that the user dismissed the original notification. I wanted to remind the user in the options that she/he should give it a try and use a different JDK to enable the JavaFX preview. 

I had in mind a label with a link - similar to the notification the user dismissed earlier. 

The PR as it is now provides the user a check box to re-enable the notification, that the user will see when she/he opens an AsciiDoc file the next time. To me this is a detour compared with a label and a link in the options directly.

I assume the solution label+link in options would come with less code and dependencies. I'd be happy it you could give it a try. 

Trying out the options dialog I noticed that URLs in labels are colored like links, but don't open as links in a browser (nothing happens). Could you dig into this and make the Kroki- and Asciidoctor-links work? 

Thanks!

**Comment by bit-man** [comment]
@bit-man please take a look and let me know if this is closer to the idea you had in mind

**Comment by ahus1** [comment]
Hello @bit-man - it is getting closer. I gave it a try but I see the label even when the user already has JavaFX available. This way it will confuse the user. A label without a link is not so much help to the user.

The layout is quite wide as the label is added to the end (not below like on all other elements)

Looking at the code changes (even when squashed) it a lot of code change for just adding a label. 

It seems to me that I it is probably too difficult for me to describe what I have in mind. Sorry for keeping you busy with this.

I'll give the issue some rest, and give it a coding effort myself in a week or two.

**Comment by bit-man** [comment]
@ahus1 sorry to hear this. It means that this PR doesn't count for Hacktoberfest?

**Comment by ahus1** [comment]
@bit-man as far as I know hacktoberfest counts the pull requests you create unless a maintainer marks them as invalid. 

Although the PR is now closed, the half that contributed to #347 is merged. This was a valuable contribution to this project. 

I will *not* mark this PR invalid, therefore it should count towards your Hacktoberfest goal. Please double-check your hacktoberfest dashboard: https://hacktoberfest.digitalocean.com/profile

As this PR is less than a week old, it should now be in "Pending" state. Once it is one week old it will turn into "Eligible".

**Comment by bit-man** [comment]
Thanks for your response

**Pull request closed without merging**
