### PR TITLE
Added different issue templates to improve GitHub workflow

### PR DESCRIPTION
**Pull request by martingreilinger**
## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [x] Other, please describe: Improved GitHub issue creation workflow

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc) document.
- [x] I have given my PR a descriptive name. If it resolves a specific issue, I referenced it in the form of `fix #xxx` (where `xxx` is the issue number).
- [ ] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.
- [ ] I have added tests to cover my changes.
- [ ] I need help writing a test to cover my change (Maintainers are willing to help).
- [x] All new and [existing](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) tests passed.

    

## Description

Provided various issue template to cover encountered topics. I tried to match the categories with existing issues and other projects. Default labels also taken from open issues.

Added useful links (_contact-links_) and disabled creation of _empty issues_ to avoid the creation of unstructured / uninstructed issues. Described [here](https://github.blog/changelog/2019-10-28-new-issue-template-configuration-options/)

### CODE REVIEW

**Comment by martingreilinger** [comment]
Issue structure and content represents my take on what could be useful.
Any feedback welcome!

**Comment by ahus1** [comment]
Thanks for adding this new issue workflow. I didn't know about this feature before. It makes sense to separate the different flows. Some re-ordering and re-writing was definitely needed.

I re-ordered and re-worded some of the templates you sent: I tried to take a users's perspective and assumed they would be non-technical/non-developers. Here some thoughts behind the changes: 

* When reporting bugs: I put the environment information at the end, as that is what users are least interested in; they want to describe their bug first. I added a sentence about "why" the environment information is needed. The trade-off would be that users will skip this part, but I'm willing to accept this.
* Avoid abbreviations: FAQ changed to Frequently Asked Questions
* Avoid telling users what to do, instead try to motivate their own interests: "Check the FAQ and trouble shooting guide before creating an issue." -> "Check the FAQ and trouble shooting guide for an existing solution."
* Avoiding technical terms like "use case" and "acceptance criteria". Instead I divided it into "why" and "how". The "why" contains information how users of the plugin (not the plugin) can benefit. The "how" would then describe existing vs new behavior. 

I pushed the changes to the branch. Please let me know what you think of these changes and if they need further improvement/polishing.

**Comment by martingreilinger** [comment]
@ahus1 thanks for the improvements, looks good in my opinion.
The simpler, non-technical wording is definitely more appealing to a broader user base!

**Comment by ahus1** [comment]
Thanks, so it's good to go -- merged!

**Comment by ahus1** [comment]
Just found that I needed to rename config.yaml to config.yml ... otherwise GitHub didn't recognize it.

**Pull request merged**
