### PR TITLE
resolves #566, adds support for the alt text attribute in the PasteImageDialog

### LINKED ISSUE #566: Support alt text property via the PasteImageDialog
## Overview:
As previously suggested in [PR #559](https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/559#issuecomment-703077250), it would be a good idea to support the alt text property via the `PasteImageDialog`

## Technical Description:
Functionality would be similar to the _include width_ field.
The dialog should consist of:
* Check box which includes or excludes the field (enables/disables the text field when checked/unchecked)
* Text field (I suggest using the `JBTextField` for its "native" feeling)

Text field validation:
* I suggest only allowing letters as this should be a descriptive text after all

During dialog submit:
* Return an `Optional<String>` which is
  * `empty` if the check box is unchecked or the field is empty
  * *contains value* if the checkbox is checked an the field is not empty

Suggested layout:
suggested-layout
(This example uses a `GridBagLayout` to increase the text field width. Additional y-padding was added to match the width input.)
**NOTE:** The input fields could benefit from a reduced y-padding and the width input could be slimmer in my opinion.
If this opinion is shared, I will create a ticket to align the width field fist.

Output:
* If a value is present it should be added to the other image arguments
  * The value should be assigned to the `alt` label (see [image attributes](https://asciidoctor.org/docs/user-manual/#summary-2))
  * The value should be quoted
  **NOTE:** It appears this does not matter based on my testing, but other attributes suggest this like `title` or `caption` so to stay consistent, I figured it would not hurt

### Acceptance Criteria:

```gherkin
Feature: Support alt text property via the PasteImageDialog

  Background:
    Given an image is pasted into an Asciidoc file

  Scenario: Alt text is included
    Given the "include alt text" check box is selected
    And the alt text "Mountain range covered in clouds" is entered
    When the dialog is submitted
    Then the created image macro should contain an "alt" attribute
    And the value should be "Mountain range covered in clouds"
```

* Include alt text: `"Mountainrange covered in clouds"`
* Output: `image::[alt="Mountainrange covered in clouds"]`

I am happy to discuss anything before I start with the implementation.
_NOTE: We can also discuss the issue structure, in regards to #564_

### PR DESCRIPTION
**Pull request by martingreilinger**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [x] Documentation
- [x] Other, please describe: Refactoring, separated PasteImageDialog and UI components

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

* Added the `alt` text field to the `PasteImageDialog`
* Moved UI components into dedicated classes and `package`
* Introduced a [light service](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_services.html#light-services) `AttributeService`, to handle the attribute string creation

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for the change. 

I reviewed the functionality and found that the code didn't escape double quotes in the alt attribute yet. I added it to the code in ImageAttributeService. It now works, but adding the quotes and the escaping now happens in ImageAttributeService, while IMHO it should happen in AttributeService. The current value object Pair doesn't allow to pass something like "alt attribute should always have quotes"... what do you think?

I also rewrote some lines in AttributeServiceTest: 
* I prefixed the "should" for each test method to describe that the method name describes an expected outcome. I didn't enforce it before. 
* the standard JUnit assert() has as first argument the expected value, then the actual value. I swapped some of the occurrences. That confused me a lot of times until I started to use AssertJ.

**Comment by martingreilinger** [comment]
@ahus1 thanks for catching that, I forgot about this case. 

So if I understand you correctly, you would preferably tell the attribute service which attributes should be quotes, to avoid mapping values manually? As well as escaping the quotes there.

How about we use simple `MacroAttribute` object in this case, instead of the `Pair`.
(Or name it `DirectiveAttribute` is that suits better? `include::` is called a _directive_ according to the writers guide, but `image`  is a _macro_? That is why I am uncertain what the correct terminology is.)

``` java
class MacroAttribute {
 Option<?> value
 Option<String> label
 boolean quoted
}
```
If `quoted` than the `(Macro)AttributeService` (which I would suggest renaming accordingly), will handle quotation and the escaping of double quotes if necessary.

Is this somewhat like what you had in mind?

And thank you for the fixes in my tests :+1:

**Comment by ahus1** [comment]
Hello @martingreilinger - I think MacroAttribute is a good name. 

Having a value holder like this is what I had in mind. You can push the quotation and escaping logic to the MacroAttributeService or to the MarcoAttribute itself. If you push the logic of quotes and escaping to MacroAttribute, the MacroAttributeService would only add the commas in between.

I leave it to you to have the logic in one place (quoting and commas in MacroAttributeService) or in two places (quoting in MacroAttribute, MacroAttributeService for the commas). 

I'm looking forward to an updated PR.

**Comment by martingreilinger** [comment]
Introduced new `MacroAttribute` which now completely handles the string mapping of itself.
Additionally added the `hasValue` method allow filtering attributes without values by the `MacroAttributeService`.

I thought about having the `MacroAttribute.asAttributeStringOption` return a `String` instead of the `Option<String>` by calling `getOrElseThrow` if not checked before, but ultimately decided against it.

Let me know what you think about my changed.

**Comment by ahus1** [comment]
Hello Martin, thank you for preparing this pull request to add this feature! As with your previous pull request, I squash and rebase this change. 

Thanks a lot for contributing to this project!

**Pull request merged**
