### PR TITLE
Feature/gradle

### PR DESCRIPTION
**Pull request by gengjiawen**
Migrate build system to gradle, related issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/126.

There are still work to do, but I am not familar with the source code.

### CODE REVIEW

**Comment by gengjiawen** [comment]
Anyone will have a review to this? I don't have the time for keep solving the conficts?

**Comment by ahus1** [comment]
I'll have a look. Anything I should now / anything that is pending?

**Comment by gengjiawen** [comment]
For now, I havn't found a bug.

**Comment by ahus1** [comment]
@gengjiawen - I've reviewed the changes and pushed some changes to the branch. 

I've moved some of the css resources to a sub folder of the resources. This should show that the css belong to jeditor or javafx.

I've also added some more dependencies to make the Markdown to Asciidoc conversion work again. 

The gradle update to 3.2 was done automatically by my IDE - I'm not familiar with gradle, but I hope it is ok. 

*one last thing*: I can run the IDE with the plugin using `gradle runIdea`. But how would I debug it? 

Once I know how to debug it I'm happy to merge it. Would you please squash all the commits into once commit?

**Comment by gengjiawen** [comment]
For debug: if you are using IntelliJ IDEA, it's quite simple to debug gradle project, just click the debug button on toolbar.
For squashing the commit: I think github provide squash, but it's on your side https://github.com/blog/2141-squash-your-commits.

**Comment by ahus1** [comment]
Alright, I added some docs and to run configurations for IntelliJ. I rebased and squashed it locally. Thanks for contributing!

**Comment by gengjiawen** [comment]
Please notice you can execute `./gradlew checkUpdates` to check dependency updates, I hope this will be convenient :)

**Pull request merged**
