### PR TITLE
Replaced the bundled Markdown to Asciidoc libraries with Maven Central dependency.

### PR DESCRIPTION
**Pull request by bodiam**
See https://github.com/markdown-asciidoc/markdown-to-asciidoc/issues/26#issuecomment-1949368800 for more info.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [x] Other, please describe: Library replacement

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

## Checklist:

- [ ] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.

Creating the pull request triggers some automated tests.
See the [chapter building in the contributor's guide](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) to find out how to run them on your local machine.

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for the PR @bodiam! I've had a look and found that there is a transitive Kotlin dependency which the AsciiDoc plugin doesn't use, so I added an exclusion. 

Let me know what you think about this. I don't know if the convert has more plans around Kotlin, or if it will be removed eventually.

**Comment by bodiam** [comment]
Hmm, good question. I wasn't aware that there's a Kotlin dependency in the library. I'll see if I can remove it from the code or if we use it for something essential. Thanks for spotting this!

**Comment by bodiam** [comment]
This version will remove the Kotlin plugin, and a whole bunch of other stuff: https://github.com/markdown-asciidoc/markdown-to-asciidoc/pull/53

**Comment by ahus1** [comment]
Thank you for the investigation. I assume it is safe to exclude the Kotlin dependency in this version. I'm merging this PR as it is already an improvement, and eventually there will be a 3.0 version with fewer dependencies.

**Comment by bodiam** [comment]
@ahus1 I'm not sure to be honest. Looking at the code, it seems like only the Kotlin version is used, not the Java version, so to make it do anything, Kotlin is required it seems. Maybe the plugin gets the Kotlin dependency from the IDE?

**Pull request merged**
