### PR TITLE
added font icon support to JavaFX preview

### LINKED ISSUE #182: add icon font support
AsciiDoc Plugin Version: 0.18.1

IDE Name and Version: 
```IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Licensed to ****** / Matthias Balke
Subscription is active until November 19, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

*Bug Description*
When using icon font, the preview doesn't display anything.

*Expected Behavior*
The icon font should be rendered in the Java FX preview pane.

*Example Code*
```adoc
:icons: font

// display an checked checkbox
icon:check-square-o[]
```

### PR DESCRIPTION
**Pull request by matthiasbalke**
This is my first try to add font-awesome to JavaFX preview. This PR closes #182.

Please review my change and tell me what you think.
When running with `runIdea` font icons are working now. But it seems way to easy.

### CODE REVIEW

**Comment by ahus1** [comment]
I've given it a try building the plugin using "buildPlugin" and it works for me as well. 

This seems to be a bit more recent than Asciidoctor's 4.6 (release notes of Asciidoctor 1.5.5), while you included 4.7 - but I don't see an issue with that. 

I briefly thought if all font files are necessary. But keeping them all and the CSS that comes with it make it easier to upgrade. And I am not sure if JavaFX behaves the same on all platforms regarding fonts. So let's keep them.

So to me it's good to go. I'll merge and publish it early next week. Until then you can build your own version of the plugin using `./gradlew -Dfile.encoding=UTF-8 buildPlugin` and give it a few test runs in you daily work.

**Comment by matthiasbalke** [comment]
@ahus1 I will downgrade font-awesome to 4.6 to avoid ugly bugs, we have to fix later on, because we don't know the exact differences between these two releases.

**Comment by ahus1** [comment]
@matthiasbalke - thanks for looking into this. The releases notes of asciidoctor state "4.6.3" to be the exact release of font awesome that is part of asciidoctor 1.5.5 (and it is still the same version in 1.5.6). 

If possible, please squash commits, so your PR contains only one commit. Alternatively you can leave that for me and I'll do then when I merge.

**Comment by mojavelinux** [comment]
It's very unlikely that the version of Font Awesome matters. We do use a few of the icons, but those icons have never changed. As long as you are on the same major version of Font Awesome, everything is expected to work the same. When you upgrade, you do enable access to new icons for use with the `icon` macro, so that's the only potential source of confusion.

**Comment by matthiasbalke** [comment]
@mojavelinux Thanks for stating this.

@ahus1 Then there is nothing more to do, then testing it in my daily business ;)

PR ready for merge.

**Comment by matthiasbalke** [comment]
The font icons in the JavaFX preview are not as sharp as they get rendered by asciidoc. Maybe thats caused by the font rendering of JavaFX?

**preview**
checkboxes-preview

**rendered**
checkboxes-rendered

**Comment by ahus1** [comment]
Font rendering in JavaFX is a strange thing to me. There are multiple settings with apparently different defaults on different platforms. 

There is a repo here: https://github.com/woky/javafx-hates-linux that shows the usage of prism.text and prism.lcdtext. There is a small text file that might give you some insight.

I haven't come around to test different settings on different platforms. Please give it a try and suggest a code change in a new pull request. 

Other plugins like the Markdown Plugin (that is also using a JavaFX preview and where i looked up most of the tricks about this) has a configuration option for one of them. But as it is a system property it will affect all plugins. 

If you think different settings make a difference, please go ahead an propose a change.

**Pull request merged**
