### PR TITLE
Fix #199 - Support zoom in preview window

### LINKED ISSUE #199: Support zoom in preview window
Comment on plugin's homepage: 

This plugin doesn't work well under high resolution screen. The font is too small. It will be much better if we can change font size(zoom) with Ctrl + Mouse Wheel. or we can change the font size.

### PR DESCRIPTION
**Pull request by ianflett**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

If adding a **new feature**:
- [x] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**
In addition to the listed aims, I've added the ability to reset zoom using Ctrl and the middle mouse button.

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this pull request! I will look at it over the next few days and merge it.

**Comment by ianflett** [comment]
You're very welcome. Have a great evening.

**Comment by ahus1** [comment]
Hello Ian, I've gave it a try and zooming in/out worked for me. 

I had problems with the zoom reset as it didn't recognize the middle button. I changed it from `mouseEvent.isMiddleButtonDown()` to to `mouseEvent.getButton() == MouseButton.MIDDLE`. Now it works for me. I pushed the change.

Could you please confirm that it still works for you as well? I tested on Windows 10, what OS did you use?

**Comment by ianflett** [comment]
That's odd. I'm using Windows 10 and I was sure it was working when I originally tested it. However, sure enough, it isn't working now. I am using a different machine, though; whether that's a factor I'm not sure.

Your fixes appear to work, however.

There is one strange thing, but I'm certain it's relating to using a slightly buggy Logitech G500 mouse. Holding the middle mouse button (with Ctrl) zooms in, so there's some zooming when you try to reset until the button is released.

**Comment by ahus1** [comment]
@ianflett - then it's probably my mouse: it's a Logitech, but it doesn't have a proper middle button. When you press the scroll wheel it just locks/unlocks the scroll wheel. I had to assign middle-click to a different button.

> Holding the middle mouse button (with Ctrl) zooms in, so there's some zooming when you try to reset until the button is released.

Do you want to leave it this way, or do you want to try to work around that (maybe by checking that the middle button is not pressed while the mouse is scrolling?)

**Comment by ianflett** [comment]
Odd that we're both using Logitechs on Windows 10 and my original code doesn't work.

Let me wait until tomorrow - I'll run some tests on the original machine. Then I can compare old and new code and see how it's affected.

If it is a Logitech thing, I don't think it matters - I think your fix is the better solution. But I'd then have more confidence about the other issue and a better idea whether it needs solving and how.

**Comment by ianflett** [comment]
Apologies, today has been frantic.

The old code still didn't work on the other machine. I'm at a loss. Not that it matters - reviewing the code again today, your version is better.

As for the odd issue I was getting, I didn't have it on the other machine, so it's clearly just my mouse.

I'd say it's good to go from my checks.

**Comment by ahus1** [comment]
Thank you again for providing this pull request. 

This idea for improvement has been around for some time, I am very excited that you picket it up for a contribution.

**Comment by ahus1** [comment]
@ianflett - as this was your first contribution to the plugin, I would appreciate it very much if you could send me a short comment how accessible this project is for contribution: was the documentation sufficient, what did you miss and would consider helpful for other first time contributors?

You can send these information to my email address that is visible in my GitHub user profile if you don't want to comment publicly.

**Pull request merged**
