### PR TITLE
fix #349 create HTML from IDE using an editor action

### LINKED ISSUE #349: Export to HTML from menu bar
There seems to be not "export to HTML" - just PDF. Any chance on implementing this?

### PR DESCRIPTION
**Pull request by balabarath**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [x] New/updated tests are included

If adding a **new feature**:
- [x] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**

fixes #349

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for your pull request - looks great! Thank you for including docs and tests already.

Please have a look at the following elements: 
* when converting adoc to HTML, don't call asciidoctor.render(), instead call asciidoctor.convertFile() with the backend "html5" -- this will give you a file on disk that is already renamed; no need to write the file by hand and figuring out a file name.
* Refactoring: the methods convertToHtml() and convertToPdf() will be so similar after this, maybe you can combine them in into one method with an extra parameter.
* to add proper HTML header/footer with CSS use OptionsBuilder....headerFooter(true). The result will be way more standard than doing it manually; but this should be done only for convertToHtml() 
* I tried out the PR and the HTML file opened in the IDE, not in a browser. Please use BrowserUtil.browse(virtualFile) to ensure that it opens in a browser, not in an IDE

Please have a look. After the change it will be ready to merge.

**Comment by balabarath** [comment]
@ahus1 I'm facing trouble with including font-awesome css file to the export. The exported html file needs font-awesome css file for the icons.
The convertFile() method doesn't add the font-awesome css file.

**Comment by ahus1** [comment]
The convertFile() method will add the font  awesome icon if (and only if) you set the icons attribute. It will include a link to a file on the CDN.

The following example works for me: 

```
:icons: font

NOTE: Hi
```

From my point of view it is now ready to be merged. Let me know if you agree; I'll then squash-and-merge the change.

**Comment by balabarath** [comment]
Please go ahead and merge the change.

**Comment by ahus1** [comment]
Thank you for this pull request to add this new functionality! I hope the documentation like the contribution guide helped. Let me know if you missed something or think something could be improved for contributors.

**Comment by balabarath** [comment]
@ahus1 Thanks for the excellent support that you have provided. The contribution document is so helpful for the new contributors like me right from setting up the environment, running tests till the development of the plugin. This is my first pull request in my entire development career. I would like to contribute more to the community. Once again thank you so much for the support you provided.

**Pull request merged**
