### PR TITLE
when clicking on preview, scroll to the source line

### PR DESCRIPTION
**Pull request by ahus1**
This is elaborating on #129 and @kastork's idea to click on the preview to scroll.

This takes a simple click (not ctrl-click as suggested).

### CODE REVIEW

**Comment by ahus1** [comment]
@kastork - you can download a preview here (I was unable to attach it in the pull request due to the size). 

https://github.com/ahus1/asciidoctor-intellij-plugin/releases/tag/0.16.0.1

Please provide you comments if it works for you (I've tested it on IntelliJ IDEA 2016.2.4)

**Comment by kastork** [comment]
Quick try... looks pretty good.  Thanks!

One behavior to think on a bit is perhaps the case of when you click on a link in the preview, it may not be the case that the user want the source to go to that link along with the preview.  I'm not necessarily expressing an opinion, just pointing out a behavior that surprised me a little.

I guess for TOC links I'd expect this.  Not sure why I _didn't_ expect it for internal links.

On a separate note, footnote links don't seem to take you to the end of the preview -- thought they did before, maybe not.

**Comment by ahus1** [comment]
I've update the code to not scroll the source view when clicking on any link (TOC, internal and external, and footnotes). 

When you want to scroll the source view after clicking on the TOC, you'll need a second click on the paragraph or headline to scroll the source view. 

I suppose this is the most consistent behaviour.

A new preview is available: https://github.com/ahus1/asciidoctor-intellij-plugin/releases/tag/0.16.0.2

**Comment by kastork** [comment]
Whichever behavior you think is most natural..  Like I said, I wasn't complaining about the linking, it just wasn't what I expected.  Congrats on the impending release.

**Comment by ahus1** [comment]
@kastork, trust your first impression when it comes to user experience. "Don't make me [the user] think" (as Steve Krug said) or the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). 

This feature is now available as part of the release [0.16.1](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.16.1). I'll use it for some days myself before I publish it on the Jetbrains plugin site.

**Pull request merged**
