### PR TITLE
resolved various deprecations and some cleanup

### PR DESCRIPTION
**Pull request by martingreilinger**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [x] Other, please describe: resolved deprecation and some cleanup (see below)

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

~~If yes,~~ please describe the breaking change:

This shouldn't cause any breaking changes most changes were internally or are invoked by Intellij.
But I suggest you do some testing yourself and see if problems do occur.

**Other information:**

_resolved deprecations_
* `Project.getBaseDir`
* `CacheManager.SERVICE.getInstance`
* `TemplateContextType.isInContext`
*  `AbstractDocumentationProvider.getCustomDocumentationElement`

_cleanup_
* extracted extension handling from `AsciiDoc` class into `AsciiDocExtensionService`
  * cleaned up syntax
  * added additional null checks
  * added tests
* aligned parameters of function declarations
* removed empty lines

_NOTE:_ Most of the changes were not covered with by unit tests, so I am unsure if I broke something. 
Did some testing myself but please test it yourself as I don't know the ins and outs of the plugin yet!

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you tackling these deprecated methods. You touched several files there, please give me some time to review it.

**Comment by ahus1** [comment]
I gave it a short local test run and will test it over the next few days. 

I removed all verify() methods as they assume a lot of internal knowledge about the tested method. IMHO tests should ensure an expected observable behavior, not internal routines. 

Ready to merge!

**Comment by martingreilinger** [comment]
@ahus1 Interesting point of view, I initially wrote the tests without them, as I have the _strict_ `when` checks.
But later decided to add them to ensure the test does really test the _desired_ branch, as otherwise the test won't necessarily fail. Because the `Optional` call chain could also _fail early_ and still produce the expected result (_empty list_).
Hope this makes sense?

Anyway, I can also see the point of your argumentation. Just an info about my though process, why I had them added.

**Comment by ahus1** [comment]
@martingreilinger - adding these might be a necessary step when creating the tests, but it would leave them brittle if they are kept in the test code.

In case you would use if() instead of streams, you could have used the test coverage tool and checked the line coverage after running all unit tests for the class. If some lines are not covered, one of the tests is not doing what you expect it to do, some lines would stay "red" in the coverage tool.

With streams you don't have branches. And line coverage works only if you would spread the lines a bit, and execute only single tests. This is the result of `shouldReturnEmptyListIfUnableToFindAsciidoctorConfig`

image

I admit this is not ideal. Damn trade-offs! 😄

**Comment by martingreilinger** [comment]
Hm, maybe this is a good indicator that the function is too complex.
Another option would be to use named functions instead of the lambdas, this would also allow a correct coverage (like when used in combination with thresholds) for tests.

Ill keep it in mind for the future!

**Pull request merged**
