### PR TITLE
resolves #287 use kroki.io to support additional diagram types

### LINKED ISSUE #287: Using kroki.io to support additional diagram types.
The latest release of the asciidoc plug-in for the Chrome browser supports a wide range of diagram types via kroki.io:

- https://kroki.io/#support
- https://twitter.com/Mogztter/status/1144293539125313539
- https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en

The upside to how this functionality is implemented, is that no client side installs of diagram tools are required. No graphviz, or other installs are needed.

At the moment if I create a mermaid diagram in IntelliJ/Asciidoc

````
[mermaid,mermaid.png]
----
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
----
````
if is of course not displayed by IntelliJ/Asciidoc

````
Failed to generate image: Could not find the 'mermaid' executable in PATH; add it to the PATH or specify its location using the 'mermaid' document attribute
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
````

but if I click on the browser ribbon in IntelliJ/Asciidoc and select Chrome, then the mermaid diagram is displayed in the browser (via kroki.io)

image

Could similar support for the diagram types supported by kroki.io be added to the asciidoctor-intellij-plugin?

### PR DESCRIPTION
**Pull request by Mogztter**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Does this PR introduce a breaking change?** (check one)

- [X] No (the new feature is disabled by default)

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [x] New/updated tests are included

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**

<strike>I believe that the diagram extension and Kroki will "conflict". So we should probably enable one or the other.</strike> done

### CODE REVIEW

**Comment by ahus1** [comment]
Look good! Yes, asciidoctor-diagram should be disabled when kroki is enabled. 
I've pushed two changes: 
* the first change makes kroki enabled/disabled part of the hash, so that the plugin creates a new instance of AsciidoctorJ when the setting changes. It also disabled asciidoctor-diagram when kroki is enabled
* there is now also a configuration dialog for kroki. You can update the texts in the properties file. For now it includes manual breaks with `<br>` as the text didn't want to wrap automatically (it can, but I didn't find out how yet)

Feel free to squash these commits with your commits. 

For this PR to be complete I'd like to see an updated FEATURES.adoc plus a unit test. The test could be added to AsciiDocTest.java, set some settings and see that the HTML created contains either plantuml elements of kroki elements.

**Comment by Mogztter** [comment]
Thanks!
I can't find the settings form in Intellij... 👀

> For this PR to be complete I'd like to see an updated FEATURES.adoc plus a unit test. The test could be added to AsciiDocTest.java, set some settings and see that the HTML created contains either plantuml elements of kroki elements.

I will do that 👍

**Comment by ahus1** [comment]
The new kroki options are just above the attribute settings in the AsciiDoc settings: 

kroki-config

**Comment by Mogztter** [comment]
I've added tests and found a few issues:

- Nomnoml, Svgbob and Mermaid only support SVG as output format
- The following syntax `plantuml::https://path/to/file.puml[]` throws an exception:

```
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `set_params' for #<OpenSSL::SSL::SSLContext:0x34558880>
2019-10-13 16:15:36,297 [  52764]   WARN - org.asciidoc.intellij.AsciiDoc - unable to render AsciiDoc document 
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `set_params' for #<OpenSSL::SSL::SSLContext:0x7f2b5758>
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:314)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:277)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:445)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:425)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:77)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:179)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:155)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:291)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.util.Alarm$Request.run(Alarm.java:382)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I've tried to add `require 'openssl'` as suggested in https://stackoverflow.com/a/20724726 but the exception is still the same.
I don't have a diagram file served over http (insecure) so I cannot check if the following is working or not: `plantuml::http://path/to/file.puml[]`.

- The syntax `erd::file://./file.erd[]` does not work but `erd::./file.erd[]` works (not a major issue in my opinion)

**Comment by ahus1** [comment]
I did several experiments. Finally the following worked: loading it earlier in the process (don't ask me why...)

The following snippet now works:

```
plantuml::https://raw.githubusercontent.com/ahus1/asciidoctor-deepdive/master/inside-documents/showcase_plantuml.puml[]
```

**Comment by Mogztter** [comment]
Awesome 👍
Any blockers left ?

I think the only remaining task is to describe this feature in `FEATURES.adoc`?
I was not really inspired today... I will try to come up with something ✍️

**Comment by ahus1** [comment]
Yes, some docs would be nice. Then it's ready to be merged. Feel free to squash commits as you like.

**Comment by Mogztter** [comment]
I've added some documentation!

> There is now also a configuration dialog for kroki. You can update the texts in the properties file. For now it includes manual breaks with <br> as the text didn't want to wrap automatically (it can, but I didn't find out how yet)

I tried to make the settings form more "flexible" to avoid the manual breaks with `<br>` as in:

dynamic-label

But it's really painful to modify and test the UI with the built-in form designer! Also the documentation is pretty much non-existent right?

Usually, when I need to create a Swing UI, I use [JFormDesigner](https://www.formdev.com/). It's not a free softward but at least creating a UI is a pleasant experience :sweat_smile:

**Comment by ahus1** [comment]
@Mogztter - thank you for this change. I'll merge it now as the the next PR is already waiting for the setting form to be changed. Feel free to open enhancements to the form as another PR, see #351

**Comment by ahus1** [comment]
> But it's really painful to modify and test the UI with the built-in form designer! Also the documentation is pretty much non-existent right?

I think it's "just" some elements wrapped in other elements the wrong way so it lost its auto-sizing. Sigh. IntelliJ includes a preview/GUI builder for the .form files. The preview is quite close to the real thing, nevertheless I didn't figure out how to enable auto-sizing here.

**Comment by Mogztter** [comment]
> IntelliJ includes a preview/GUI builder for the .form files. 

I didn't find the button, I will check again.
Do we have to use JetBrains components exclusively (ie `JBLabel`) or can we use Swing components too (`JTextPane`...)?

**Pull request merged**
