### PR TITLE
Open links to Windows absolute paths from xrefs.

### PR DESCRIPTION
**Pull request by ropelli**
URI for a Windows path `C:/foo/bar` reports scheme as `C`.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [x] No
- [ ] Yes

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/CONTRIBUTING.adoc) document.
- [x] I have given my PR a descriptive name. If it resolves a specific issue, I referenced it in the form of `fix #xxx` (where `xxx` is the issue number).
- [ ] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.
- [ ] I have added tests to cover the changes in the code.
- [x] I need help writing a test (Maintainers are willing to help).

Creating the pull request triggers some automated tests.
See the [chapter building in the contributor's guide](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html) to find out how to run them on your local machine.

## Notes
It's not the best or elegant solution but in my opinion simple. In my use case I am having .asciidoctorconfig to define paths using asciidoctorconfigdir variable which will give me an absolute path. Using that works with includes but not with xrefs in the IDE preview and I get warnings like:
```
WARN - #o.a.i.e.j.AsciiDocJCEFHtmlPanel - won't open URI as it might be unsafe: C:/foo/bar/project/my-doc.html
```
I haven't been able to test this change yet but I want to open the discussion. Also if unit tests are needed for the change, I need help on them.

### CODE REVIEW

**Comment by ahus1** [comment]
Thanks for contributing this PR! I suppose this will go without a unit test as this code hasn't really been designed for that. 

I'd like to test it manually ... could you please provide an example AsciiDoc `.asciidoctorconfig` file plus an example with an `xref:[]` for me to test?

**Comment by ropelli** [comment]
I suppose, in the simplest case, you could just use the built-in `{asciidoctorconfigdir}` in your `xref:[]` and try to reference any file in the project when you have an empty `.asciidoctorconfig` in the root of the project.

Detailed instructions to reproduce the issue:
1. Open IntelliJ IDEA with Asciidoctor plugin installed in Windows operating system
2. Create any kind of empty project in IntelliJ.
3. Place an empty `.asciidoctorconfig` in the root of the project.
4. Create an empty `foo.adoc` file in the root of the project.
5. Create `bar.adoc` and write `xref:{asciidoctorconfigdir}/foo.adoc[]` in it.
6. Click the link in the preview -> nothing happens but the error is found in Intellij IDEA log file.

**Comment by ahus1** [comment]
Thank you for the PR. When testing this, I found that another change was needed in the openInEditor() code; I added this to the PR and will now merge it. I'll let you know as soon as a pre-release with this change is available.

**Comment by ahus1** [comment]
This change is now part of the pre-release 0.37.50. Please give it a try and let me know if it works for you as you would expect it to work.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ropelli** [comment]
Seem to work nicely! @ahus1, thank you for you efforts! And I see there is already a official release and the plugin updated automatically from IDE.

**Comment by ropelli** [comment]
I think, the issue is back. Not sure since which version.

**Pull request merged**
