### PR TITLE
initial implementation of parser, PSI and structure view for AsciiDoc

### PR DESCRIPTION
**Pull request by yole**

### CODE REVIEW

**Comment by bodiam** [comment]
Hi Dmitry! Thanks again. Is this already doing basic syntax highlighting? Or does it need even more?

**Comment by mojavelinux** [comment]
> Or does it need even more?

I'm sure it will always need more as the syntax for AsciiDoc goes pretty deep. However, as Dmitry has pointed out, just having the basic structure covered already helps a tremendous amount. We just need to chip away at it a bit at a time and eventually the coverage will come.

**Comment by bodiam** [comment]
Hi Dan, I was being unclear. I know it only does basic parsing of bold/italic/etc. However, my question was if this version already does that, or if more IntelliJ components are needed to get the basic highlighting visible in IntelliJ.

**Comment by mojavelinux** [comment]
Gotcha. I'm quite curious myself. I'll try to fire it up IntelliJ soon to give it spin.

**Comment by yole** [comment]
It already highlights comments, headings and listing blocks.

**Comment by bodiam** [comment]
Super! Can you also do bold, and give me some instructions on what you did? Then I can repeat the same for italic, strikethrough, inline code, etc.

**Pull request merged**
