### PR TITLE
fix #358 - added some live templates for config attributes

### LINKED ISSUE #358: Add live template for config section
The pre-defined live templates are a great feature!
A template which shows examples for the various config attributes of AsciiDoc could be helpfull since it is hard to remember them all. Maybe we could cluster them:

```
ad-config-i18n
:caution-caption: Caution
:important-caption: Important
:note-caption: Note
:tip-caption: Tip
:warning-caption: Warning
:appendix-caption: Appendix
:example-caption: Example
:figure-caption: Figure
:table-caption: Table
:toc-title: Table of Contents
```
```
ad-config-toc
:toc-title: Table of Contents
:toc-placement: auto
:toclevels: 4
:sectnums:
:sectnumlevels: 2
:sectanchors:
:sectids:
:sectlinks:
```

```
ad-config-pdf
:pdf-page-size: A4
:pdf-stylesdir: ../pdfTheme

```

```
ad-config-render
:icons: font
:imagesdir: images
::doctype: book
```

I guess the change has to be applied to https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/resources/liveTemplates/AsciiDocLiveTemplates.xml

### PR DESCRIPTION
**Pull request by rdmueller**
**What kind of change does this PR introduce?** (check at least one)

- [X] Feature

**Does this PR introduce a breaking change?** (check one)

- [X] No

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

Changes have been manually tested

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

no need to, since it is only a sub-feature

### CODE REVIEW

**Comment by ahus1** [comment]
Thank you for this PR. I've reviewed the i18n config template and made some changes: 

* an extra line of explanation what to see here to make it easier to learn AsciiDoc syntax. This might not be necessary for all templates, but I see a benefit of a one-line summary for this very long template.
* each attribute value as a template variable, so a Enter takes the user from one value to the next
* a space after the "//" for the line comment. I'd argue this is more common

Please give it a review. If you agree, please apply it to the other templates as well. Please discuss where you don't agree.

livetemplate

**Comment by rdmueller** [comment]
thanx. I will update the other templates according to your suggestions

**Comment by rdmueller** [comment]
ok. I've updates the templates to my best knowledge :-)

**Comment by ahus1** [comment]
Thank you for your change. I squashed&merged it to the master branch. I've also added partnums to the built-in documentation of attributes (you can open these using Ctrl-Q when the cursor is hovering over the attribute name. I'm preparing a change that this will also work when your cursor is in the attribute value.

**Pull request merged**
