### PR TITLE
adding support AsciiDoc context for live templates

### PR DESCRIPTION
**Pull request by ahus1**
I prepared a first draft to support AsciiDoc language context within Live Templates. 

Using this, you can restrict your favourite live template to only AsciiDoc files. 

adlivetemplate

I want to supply some default templates with the plugin - any suggestions? A starter would could be a two-column table with a heading (but I know that table wizard is underway). 

Suggestion for `tbl2` = "Two Column Table" template:

    |===
    | $cell1header$ | $cell2header$
    
    | $cell1row1$ | $cell2row1$
    | $cell1row2$ | $cell2row2$
    |===

Please paste your favourite template here so we can supply some standard templates.

### CODE REVIEW

**Comment by ahus1** [comment]
It started to work once I added  the new resource folder with the templates to `asciidoctor-intellij.iml`. 
The first template `tbl2` is now included. Ready when you are (for merge)! 

BTW: Happy new year! :four_leaf_clover:

**Comment by mojavelinux** [comment]
Happy New Year to you. It's going to be a great year for AsciiDoc writers &
tooling! 📝💻🎉

**Comment by bodiam** [comment]
Thanks for putting the effort in this! I'm trying to release a new version ASAP!

**Comment by mojavelinux** [comment]
:+1:

**Comment by bodiam** [comment]
Hi @ahus1 , I've merged the change, but are we sure we really wanna do it like this? Now, every time you press the 't' character in an AsciiDoc document, the templates are shown. I'd prefer to show them only when pressing CMD+J. What do you think?

**Comment by ahus1** [comment]
Hello @bodiam - thank you for the comment. 

I think the way it is now is consistent with other programming editors in intellij:
  * when I press `f` in a Java context, the IDE suggests `fori` as a live template (among other suggestions)
  * when I press `s` in a Java context, the IDE suggests `serr`, `souf` and other live templates with a lot of other suggestions. 

Do you have an example (maybe with another plugin and/or language support) for me where the templates are only shown when pressing `CMD`+`J`?

Please re-open this PR so we can track the discussion.

Thanks,
Alexander.

**Comment by bodiam** [comment]
Hi @ahus1, I don't think I can reopen the PR, since I've already merged it. I think that for my Bootstrap 3 plugin does this, but I'm not sure why to be honest. 

Note that I don't have a strong opinion about this, I was just surprised with the behaviour and I'm fine with either!

**Comment by ahus1** [comment]
Hi @bodiam, I see the different behaviour in the HTML editor where templates only appear once you press CMD-J compared to the asciidoctor (default?) editor. But have no idea on how to change this... I believe this is a default behaviour. Therefore I leave it like this.

**Pull request merged**
