### PR TITLE
Use the official Asciidoctor icon

### PR DESCRIPTION
**Pull request by kharaone**
Following the descriptions of https://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html
used 16x16 of filled svg and added the retina-based version as a 32x32

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm not liking how these turned out. I'm going to see if I can make a version with a bit better quality and clarity. We are pushing the boundaries of the design at 16x16, so some tweaking may be necessary.

**Comment by kharaone** [comment]
I hesited to change the stroke as it's an Intellectual Property ^^
You definitely made the icon more readable

**Comment by mojavelinux** [comment]
You are correct. You did exactly the right thing. This was a change I needed to make on behalf of the project. And I'm glad you prompted me to finally get it done ;)

**Comment by mojavelinux** [comment]
The 16x16 logo might still be a bit fuzzy. However, I have a HiDPI screen, so when I test it I see the higher quality logo. And I'm very happy with how it looks.

**Comment by ahus1** [comment]
thank you for these contributions, @kharaone and @mojavelinux! Happy Hacktober!

**Comment by mojavelinux** [comment]
:beers:

**Pull request merged**
