### PR TITLE
initial implementation of syntax highlighting for asciidoc

### PR DESCRIPTION
**Pull request by yole**

### CODE REVIEW

**Comment by bodiam** [comment]
Hi Dmitry, thank you for this great contribution!

**Comment by yole** [comment]
There's more to come. :)

**Comment by bodiam** [comment]
Looking forward to it! This feature will be an important building block for so many extra features!

**Comment by mojavelinux** [comment]
This is very exciting. We really need a grammar / reference parser for the AsciiDoc syntax and this another step down that road.

What might help to get other people involved (including myself) is to start creating an acceptance testing suite for what the grammar matches so that we can review and validate that it's accurate. I feel like there's a lot of stuff about AsciiDoc parsing that's stuck in my head and with a test suite I can follow, it will help me help you with the details.

Thanks again for kicking off this initiative!

**Comment by mojavelinux** [comment]
To clarify my comment about the test suite, I see that there is a low-level unit test but I was thinking about something more along the lines of a document-oriented test that's a bit easier to study. Having said that, I do think the unit test is a good start.

**Comment by bodiam** [comment]
Dan, good comments! And while I agree with you, I feel that the discussion of creating a grammar / reference parser can better take part in it's own topic in the issue tracker or on the AsciiDoc forum, instead of the comments for the IntelliJ parser, agreed?

**Comment by bodiam** [comment]
@harrol Completing this makes implementing the Scratch files also possible!

**Comment by mojavelinux** [comment]
> I feel that the discussion of creating a grammar / reference parser can better take part in it's own topic...

Yes, I agree. I'm just pointing out that this is closely related and decisions will need to be made in the process of creating this lexer regardless.

**Comment by yole** [comment]
As for me, I'm afraid I won't have time to implement a comprehensive lexer/parser that supports all asciidoc features. I'm sorely missing basic syntax highlighting, structure view and a couple of inspections when working on my book project, but I'm only using a subset of features of the markup, and once I have those covered, I'll have to focus on the book and not on improving the plugin further.

Of course, this should still work as a foundation for other people to build upon.

**Comment by mojavelinux** [comment]
> this should still work as a foundation for other people to build upon.

Exactly. That's how we roll.

**Comment by harrol** [comment]
@yole Very cool! @bodiam Let's have a look at scratch files

**Pull request merged**
