### PR TITLE
Table creation through UI in the toolbar and paste special (for examp…

### LINKED ISSUE #92: Create Table Dialog improvements?
Hi,

I began messing around with the create table dialog. Before I put much more effort into that (and make it so that I can make a PR for that) I would like to know what you think about it.

What I done so far is to replace the check box for the title with a text field for the title, so that this can be entered directly in the dialog. Not typing anything there (empty string) is equal to not checking the box.

What I would like to work on is to allow some data-entering in a spreadsheet-like way. Not sure how to do that yet, my skills in swing are quite rusty, but I think this could be a fun task and I think it would improve the UI.

So, what do you think about that?

### PR DESCRIPTION
**Pull request by bbrenne**
…le from csv).

resolves #92 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing documents:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding
- [ ] New/updated tests are included

If adding a **new feature**:
- [ ] Feature documentation is updated: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc

**Other information:**

### CODE REVIEW

**Comment by ahus1** [comment]
@bbrenne - thank you for this PR! It works very nice for me (I can even copy and paste from a spreadsheet now!)

I did some touch-up on code formatting and null handling: I got a UnsupportedFlavorException when I had an image in the clipboard. This lead later on to a null pointer exception. The updated version now shows "unable to parse clipboard" in the dialog when this happens. 

I wonder if you could investigate the following:
* A user who selects "Paste Special" might be lost about the functionality she/he has just selected. A short text displayed by PasteTableDialog could help. The text should explain in one or two sentences what the user can achieve here (create new table from contents of the clipboard) and what the user needs to do as a pre-requisite (copy something to the clipboard)
* can you disable the OK button if the clipboard can't be parsed (or if the clipboard is empty)? In these cases it wouldn't make sense to continue with OK.
* The dialog appear in the context menu as "Paste Special..." - wouldn't it be better to rename it to "Paste Table..." (like the title of the title of the dialog)? 
* Should there be a checkbox like "use first row as header"? Otherwise it would be quite tedious to re-format the first row.

Thanks!

**Comment by bbrenne** [comment]
Thanks for the review, I'll rework it  when I can.

**Comment by bbrenne** [comment]
Do you think I should use _Header 1|Header2, etc_ when the first row is not used or should I define a table without header (using _[cols="x"]_)

**Comment by ahus1** [comment]
I would keep the "Header 1|Header2" as I assume tables with headers are more common than tables without header and the user would probably want to add the header after the paste.

**Comment by ahus1** [comment]
Thank you for this contribution! I assume this will help users a lot.

When I implemented the extract/inline include directive feature I came across the doValidate() method. I moved the content of update() to this method. This allowed me to remove some boiler plate code. I only learned about this yesterday; the SDK API is quite huge :-/

**Pull request merged**
